# Generated by Django 4.2.5 on 2023-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='Нет описания', max_length=255),
        ),
    ]
